name: app_movil
description: "Sistema de gestiÃ³n de reclamos telecomunicaciones"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.0

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.0
  pretty_dio_logger: ^1.3.1

  # Storage
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # UI
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Push Notifications
  onesignal_flutter: ^5.1.0

  # File Picker
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  badges: ^3.1.2

  # Utils
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
